Prepare auto-updating installer with default plugins and customizations
eclipse-theia/theia-example pull request #15
Opened 2020-12-03 08:12 UTC by jfaltermeier

* add preinstalled theiaPlugins to package-json of electron-app (preparation for #5)
* add lerna to enable a multi-package repository for electron app + customization packages
* add a custom main js that sets the environment variable for preinstalled plugins
* add a customization module for the installer at theia-example-updater. This may be used to enable updates (#13), to customize the about dialog (#10), and to customize the getting started page (#9)

Signed-off-by: Johannes Faltermeier <jfaltermeier@eclipsesource.com>
Signed-off-by: Lucas Koehler <lkoehler@eclipsesource.com>
Contributed on behalf of STMicroelectronics

#### What it does

#### How to test

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2020-12-08 00:34 UTC, koegel commented
@thegecko would you be available for reviewing this PR?

2020-12-12 13:13 UTC, thegecko requested changes
I need to look into getting PRs built on jenkins so we know a merge won't break master. Aside from that there are a few minor comments

2020-12-12 13:13 UTC, thegecko commented on theia-example-updater/package.json
> +    "build": "tsc --build base.tsconfig.json"
This should use a local `tsconfig.json` file which inherits from the base one. The base one should be put in the root of the monorepo for use/exension by other packages

2020-12-14 08:08 UTC, jfaltermeier commented on electron-app/electron-builder.yml
> +appId: eclipse.theia.java
This was an oversight and I'll remove it. Initially the only plugins that were preinstalled during testing were Java related.

2020-12-14 08:08 UTC, jfaltermeier commented on electron-app/electron-builder.yml
> +publish:
I'll remove it. We can add the proper configuration with #13 for deployment on a generic HTTP server like the Eclipse servers.

2020-12-14 08:09 UTC, jfaltermeier commented
Thanks for the review. We addressed the comments and rebased the changes on the latest master

2020-12-14 15:42 UTC, thegecko commented
Thanks for the updates. As I find time I'm modifying jenkins to build PRs and see whether this passes.

2020-12-15 12:38 UTC, thegecko commented
Can you rebase this on master and resolve the conflict?

2020-12-15 15:08 UTC, jfaltermeier commented
Sure, conflict is resolved

2020-12-15 15:13 UTC, thegecko commented
[building...](https://ci.eclipse.org/theia/job/theia-example/view/change-requests/job/PR-15/)

2020-12-15 16:07 UTC, thegecko commented
The windows build failed with:

```
cannot find specified resource "LICENSE", nor relative to "C:\Users\genie.theia\jenkins_agent\workspace\theia-example_PR-15\electron-app\resources", neither relative to project dir ("C:\Users\genie.theia\jenkins_agent\workspace\theia-example_PR-15\electron-app")
```

Which suggests a file path is wrong with `LICENSE`.

There's also Mac issues, but that's likely to do with the `node` upgrade being done on there.

2020-12-16 09:14 UTC, thegecko commented
Thanks, looks like the changes have fixed Windows. We are just waiting on the node upgrade on the mac agent:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=568685

2020-12-16 15:08 UTC, thegecko commented
The node upgrade is complete and this PR now fails during signing.

This is due to how jenkins undertakes builds. As this this PR is untrusted (opened from a fork), therefore it uses the origin `jenkinsfile` (from `master`) to undertake the build and due to the output files moving from `dist` it can't find them.

There are a few ways forward:
- Slacken the security to trust all PRs from forks (not ideal)
- Split the `Jenkinsfile` update out of this PR and merge it separately from a branch (will break `master`)
- Have this PR submitted from a branch rather than a fork

Are you able to reopen this from a branch (if you have the rights?)

2020-12-16 16:14 UTC, thegecko commented
Apologies, I've just merged the 1.8.0 release ahead of this too so another rebase is required.

2020-12-17 09:06 UTC, jfaltermeier commented
I've updated the PR to 1.8. Also I've tried to push my changes to a branch in this repository, however I don't have the rights. 
So should I remove the jenkinsfile changes from this PR? (I think we've only updated paths, because the dist directory is now nested within the electron-app directory rather than at the root)

2020-12-17 09:40 UTC, thegecko commented
> I've updated the PR to 1.8

Thanks!

> should I remove the jenkinsfile changes from this PR?

I guess it won't work without that change unless you can think of a way of it can keep the paths?

> I've tried to push my changes to a branch in this repository, however I don't have the rights

OK, I'll see what I can do

2020-12-17 15:14 UTC, thegecko commented
@jfaltermeier can you rebase this PR again and use the [`distFolder` variable](https://github.com/eclipse-theia/theia-example/blob/master/Jenkinsfile#L6) in the `jenkinsfile` rather than the inline changes to `dist`?

I can then run your PR end-to-end.

2020-12-18 07:35 UTC, jfaltermeier commented
Thanks, jenkinsfile is updated now

2020-12-18 14:58 UTC, merged

2020-12-18 14:58 UTC, thegecko commented
Looks like it built! Merging.

2020-12-18 18:05 UTC, thegecko commented
Merge succeeded, the latest 1.8 release here should include your changes, but I haven't tested it:

https://download.eclipse.org/theia/

2020-12-21 09:40 UTC, jfaltermeier commented
Thank you, looks good!